apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
spec:
  replicas: 1 # Adjust as needed
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          env:
            - name: OLLAMA_BASE_URL
              value: http://ollama-service:11434
            - name: WEBUI_AUTH
              value: "False"
          ports:
            - containerPort: 8080
            # hostPort: 8080 # uncomment for local cluster
          volumeMounts:
            - name: open-webui-data
              mountPath: /app/backend/data
      volumes:
        - name: open-webui-data
          hostPath:
            path: /data/open-webui # local path on the node, or use PVC for a cluster
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
spec:
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 8080 # External port
      targetPort: 8080 # Container port
  type: ClusterIP
