name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build-fastsdcpu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: fastsdcpu
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/fastsdcpu:${{ github.sha }}
            ghcr.io/${{ github.repository }}/fastsdcpu:1.0.0-beta.100
            ghcr.io/${{ github.repository }}/fastsdcpu:latest
          build-args: |
            BUILD_DATE=${{ github.run_number }}

  build-sd-cpp-webui:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: sd-cpp-webui
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/sd-cpp-webui:${{ github.sha }}
            ghcr.io/${{ github.repository }}/sd-cpp-webui:latest
          build-args: |
            BUILD_DATE=${{ github.run_number }}

  build-ollama:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./ollama-cuda
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ollama-cuda:${{ github.sha }}
            ghcr.io/${{ github.repository }}/ollama-cuda:latest
